# Configurações do Servidor
server.port=8081

# Configurações da Aplicação
spring.application.name=SportsCenter

# Configuração do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/sports_senter_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Configuração do Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Ordena os endpoints por método HTTP e depois por caminho alfabético
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha